### ISSUE TITLE
explain (SETTINGS on)

### ISSUE THREAD

**Issue by legrandlegrand** [cybertec-postgresql/pg_show_plans#1]
Hello,
First of all, thank you for this so long awaited extension, that works without needing any patch on core ! This is really helpfull !!!

I wanted to know if you thought about adding the **explain SETTINGS** parameter( available with pg12 and more), that permits to see all the modified parameters from the query execution context ?

Most monitored parameters as described here
https://fluca1978.github.io/2019/12/05/Explain_settings.html

Regards
PAscal

**Comment by s-hironobu** [comment]
Currently, we have no plan to support it. The reasons are:

(1) to keep this extension simple.

(2) the changed parameters can be shown anytime by using the EXPLAIN command because users set the parameters as GLOBAL parameters. (In other words, it is not usual if you change the parameter values as LOCAL parameters in each session.)

Best regards,

**Comment by legrandlegrand** [comment]
**(1) to keep this extension simple**.
Ok, I agree that it is better to keep it simple.
It is also simple to customize pg_show_plans.c:

es->settings=true; // added line
ExplainBeginOutput(es);
ExplainPrintPlan(es, queryDesc);
ExplainEndOutput(es);

note that as long as gucs haven't been modified, 
explain output (with or without SETTINGS)
is identical.

I didn't test to know what is the overhead of this option ...


**(2) the changed parameters can be shown anytime by using the EXPLAIN command** 
Not really, because It is not possible to explain statement from an other session
where search_path or enable_seqscan have been locally modified:
there is no way to now that such modifications have been done ...

You can close it if you want, as (1) is more important,
or let it opened to see what other people think about it ;o)

maybe one day you'll add an other pgsp parameter to set settings ON or costs OFF
Regards
Pascal

**Comment by s-hironobu** [comment]
This is not a private product, so we have to consider how to maintain this source code.
If we support this feature, we don't only add the code to put this feature, but also we must make a branch to support this feature upper version 12, moreover, we have to test.


If you need this feature, you can add to your environment.

**Comment by legrandlegrand** [comment]
So yes, I have added (SETTINGS on) to my environment,
in conjonction with (COSTS off) that has less overhead.
Like that I'm able to rebuild the execution context of queries to launch EXPLAIN ANALYZE.

Regards
PAscal
