### ISSUE TITLE
performances: getpid() vs MyProcPid

### ISSUE THREAD

**Issue by legrandlegrand** [cybertec-postgresql/pg_show_plans#11]
Hello,
playing with
do $$ declare i int;j int; begin for i in 1..1000000 loop select 1 into j; end loop; end; $$;
and pg_show_plans_enable()

perf tool on my Ubuntu server is showing an high cpu activity arround _getpid.
Replacing getpid() with MyProcPid in pg_show_plans seems to help.

Maybe you will be able to reproduce.
regards
PAscal

**Comment by s-hironobu** [comment]
I'll improve the next version. Thanks.
