### ISSUE TITLE
Update the Readme to show how to create Makefile.global

### ISSUE THREAD

**Issue by alchemistmatt** [cybertec-postgresql/pg_show_plans#13]
The Readme shows these steps for building and installing the pg_show_plans extension:
```
$ tar xvfj postgresql-12.2.tar.bz2
$ cd postgresql-12.2/contrib
$ git clone https://github.com/cybertec-postgresql/pg_show_plans.git
$ cd pg_show_plans
$ make && make install
```
When I followed these steps, I saw these errors:
```
Makefile:16: ../../src/Makefile.global: No such file or directory
Makefile:17: /contrib/contrib-global.mk: No such file or directory
```
After some searching, I found a page describing [Installing PostgreSQL from source](https://www.tecmint.com/install-postgresql-from-source-code-in-linux/) and learned I needed to do this:
```
$ cd postgresql-12.2
$ ./configure --prefix=/usr/pgsql-12
```
where the path specified for `prefix` is the path to the postgresql instance on the server.  Having done this, the missing files were created:
* Makefile.global
* Makefile.port -> ../src/makefiles/Makefile.linux

I could then proceed with the build and install
```
$ cd postgresql-12.2/contrib
$ git clone https://github.com/cybertec-postgresql/pg_show_plans.git
$ cd pg_show_plans
$ make
$ sudo make install
```
I suggest you update your Readme.md file to include the `configure` step.  

I also suggest you also add an example wget command
```
$ wget https://ftp.postgresql.org/pub/source/v12.2/postgresql-12.2.tar.bz2
$ tar xvfj postgresql-12.2.tar.bz2
```
Thank you for making this tool available.

**Comment by harrylewis** [comment]
Hey @alchemistmatt 👋 

I came across this issue myself, and your guidance helped me. I also discovered in the PostgreSQL documentation, a page on doing an [Installation from Source Code](https://www.postgresql.org/docs/current/installation.html), which covers this step too, so I wonder if this constitutes enough documentation for it?
