### ISSUE TITLE
When I make a query, a transaction ID will be consumed

### ISSUE THREAD

**Issue by xiongcc1972** [cybertec-postgresql/pg_show_plans#19]
hi, 
when i used the follow sql: select * from pg_show_plans，and then i execute select txid_current()，i find current transaction id has increased by 2
postgres=# select txid_current();
 txid_current 
--------------
     11057183
(1 row)

postgres=# select * from pg_show_plans ;
  pid  | level | userid |  dbid  |                                 plan                                  
-------+-------+--------+--------+-----------------------------------------------------------------------
 20100 |     0 |     10 | 333744 | Function Scan on pg_show_plans  (cost=0.00..10.00 rows=1000 width=56)
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11057185
(1 row)

Will this cause the transaction ID Wraparound quickly?

**Comment by laurenz** [comment]
Duplicate of #20.
