### ISSUE TITLE
Query consumes transaction ID

### ISSUE THREAD

**Issue by xiongcc1972** [cybertec-postgresql/pg_show_plans#20]
hi,

when i used the follow sql: select * from pg_show_plans，and then i execute select txid_current()，i find current transaction id has increased by 2
postgres=# select txid_current();
txid_current
 11057183
(1 row)

postgres=# select * from pg_show_plans ;
...

postgres=# select txid_current();
txid_current
 11057185
(1 row)

Will this cause the transaction ID Wraparound quickly?

**Comment by laurenz** [comment]
That function takes a light-weight lock, which I guess requires a transaction ID.

If you keep calling the function all the time, you will consume transaction IDs quickly. Otherwise it shouldn't be a problem.

**Comment by xiongcc1972** [comment]
Sorry, maybe I didn’t express it clearly. For read-only queries, such as select id from test, transaction ID will not be consumed, just virtual transaction id，but after loading pg_show_plans,comman queries will also consume Permanent transaction ID, even if select 1，this will cause transaction ID Wraparound quickly

**Comment by xiongcc1972** [comment]
just like this：
postgres=# select txid_current();
 txid_current 
--------------
     11479106
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479110
(1 row)


and this is the case without loading pg_show_plans
postgres=# select txid_current();
 txid_current 
--------------
     11479104
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479105
(1 row)

**Comment by xiongcc1972** [comment]
more detail

postgres=# select txid_current();
 txid_current 
--------------
     11479104
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479105
(1 row)

**Comment by xiongcc1972** [comment]
I will give more detailes
this is the case with loading pg_show_plans:

postgres=# select txid_current();
 txid_current 
--------------
     11479106
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479110
(1 row)


and the case without loading pg_show_plans:
postgres=# select txid_current();
 txid_current 
--------------
     11479104
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479105
(1 row)

**Comment by xiongcc1972** [comment]
> Sorry, maybe I didn’t express it clearly. For read-only queries, such as select id from test, transaction ID will not be consumed, just virtual transaction id，but after loading pg_show_plans,comman queries will also consume Permanent transaction ID, even if select 1，this will cause transaction ID Wraparound quickly

I will give more detailes
this is the case with loading pg_show_plans:

postgres=# select txid_current();
 txid_current 
--------------
     11479106
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479110
(1 row)


and the case without loading pg_show_plans:
postgres=# select txid_current();
 txid_current 
--------------
     11479104
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479105
(1 row)

**Comment by xiongcc1972** [comment]
I will give more detailes
this is the case with loading pg_show_plans:

postgres=# select txid_current();
 txid_current 
--------------
     11479106
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479110
(1 row)


and the case without loading pg_show_plans:
postgres=# select txid_current();
 txid_current 
--------------
     11479104
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479105
(1 row)

**Comment by xiongcc1972** [comment]
`I will give more detailes
this is the case with loading pg_show_plans:

postgres=# select txid_current();
 txid_current 
--------------
     11479106
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479110
(1 row)


and the case without loading pg_show_plans:
postgres=# select txid_current();
 txid_current 
--------------
     11479104
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479105
(1 row)`

**Comment by xiongcc1972** [comment]
**I will give more detailes
this is the case with loading pg_show_plans:

postgres=# select txid_current();
 txid_current 
--------------
     11479106
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479110
(1 row)


and the case without loading pg_show_plans:
postgres=# select txid_current();
 txid_current 
--------------
     11479104
(1 row)

postgres=# select 1;
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1;
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current();
 txid_current 
--------------
     11479105
(1 row)
**

**Comment by xiongcc1972** [comment]
I will give more detailes
this is the case with loading pg_show_plans:

 select txid_current();
 txid_current 
--------------
     11479106
 

 select 1;
 ?column? 
----------
        1
 

 select * from test limit 1;
 id 
----
  1
 

 select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
 

 select txid_current();
 txid_current 
--------------
     11479110
 


and the case without loading pg_show_plans:
 select txid_current();
 txid_current 
--------------
     11479104
 

 select 1;
 ?column? 
----------
        1
 

 select * from test limit 1;
 id 
----
  1
 

 select relname from pg_class limit 1;
     relname     
-----------------
 pg_toast_333812
 

 select txid_current();
 txid_current 
--------------
     11479105

**Comment by xiongcc1972** [comment]
I will give more detailes
this is the case with loading pg_show_plans:

postgres=# select txid_current() 
 txid_current 
--------------
     11479106
(1 row)

postgres=# select 1 
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1 
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1 
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current() 
 txid_current 
--------------
     11479110
(1 row)


and the case without loading pg_show_plans:
postgres=# select txid_current() 
 txid_current 
--------------
     11479104
(1 row)

postgres=# select 1 
 ?column? 
----------
        1
(1 row)

postgres=# select * from test limit 1 
 id 
----
  1
(1 row)

postgres=# select relname from pg_class limit 1 
     relname     
-----------------
 pg_toast_333812
(1 row)

postgres=# select txid_current() 
 txid_current 
--------------
     11479105
(1 row)###

**Comment by laurenz** [comment]
Ah, I see. I guess I'll have to leave this to @s-hironobu to answer, but it looks like a bug to me.

**Comment by s-hironobu** [comment]
Done.
