### ISSUE TITLE
pg_show_plans.max_plan_length，What does it have to do with?

### ISSUE THREAD

**Issue by Runbacktoo** [cybertec-postgresql/pg_show_plans#22]
I tried to set the value to 20000, but an error was reported when I restarted the database, 
[18663] FATAL: out of memory
Because I don’t know how many bytes the plan will have, I want to set it as large as possible

**Comment by s-hironobu** [comment]
pg_show plans allocates approximately (max_plan_length * max_connecions * 5) bytes on the shared memory to store plans, Therefore, if the value of max_plan_length is too large, PostgreSQL may not start due to an out of memory error.
