### ISSUE TITLE
Postgresql 15 pg_show_plans.so: undefined symbol: elog_finish

### ISSUE THREAD

**Issue by PavelSorokin** [cybertec-postgresql/pg_show_plans#28]
Hi, version 1.1 support pg15?
And i install without errors in pg12

[oracle8 pg_show_plans]$ sudo make install
/usr/bin/mkdir -p '/usr/pgsql-15/lib'
/usr/bin/mkdir -p '/usr/pgsql-15/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-15/share/extension'
/usr/bin/install -c -m 755  pg_show_plans.so '/usr/pgsql-15/lib/pg_show_plans.so'
/usr/bin/install -c -m 644 .//pg_show_plans.control '/usr/pgsql-15/share/extension/'
/usr/bin/install -c -m 644 .//pg_show_plans--1.0--1.1.sql .//pg_show_plans--1.1.sql  '/usr/pgsql-15/share/extension/'
/usr/bin/mkdir -p '/usr/pgsql-15/lib/bitcode/pg_show_plans'
/usr/bin/mkdir -p '/usr/pgsql-15/lib/bitcode'/pg_show_plans/
/usr/bin/install -c -m 644 pg_show_plans.bc '/usr/pgsql-15/lib/bitcode'/pg_show_plans/./
cd '/usr/pgsql-15/lib/bitcode' && /usr/bin/llvm-lto -thinlto -thinlto-action=thinlink -o pg_show_plans.index.bc pg_show_plans/pg_show_plans.bc

/usr/pgsql-15/bin/pg_ctl -D /var/lib/pgsql/15 start
waiting for server to start....2023-05-19 11:42:23.041 UTC [83599] FATAL:  could not load library "/usr/pgsql-15/lib/pg_show_plans.so": /usr/pgsql-15/lib/pg_show_plans.so: undefined symbol: elog_finish
2023-05-19 11:42:23.041 UTC [83599] LOG:  database system is shut down

OS
Red Hat Enterprise Linux release 8.7 (Ootpa)

**Comment by df7cb** [comment]
Yes, PG15 is supported.

The most likely problem is that the build targeted the wrong PG version. Try `make clean` and running the build again with the correct pg_config version, `make install PG_CONFIG=/usr/pgsql-15/bin/pg_config`.

**Comment by PavelSorokin** [comment]
thx, i am first make in pg12 
after run make clean and make install , postgres-15 was started
