### ISSUE TITLE
Nested plans after level 0 join their text with subsequent level plans

### ISSUE THREAD

**Issue by monok0** [cybertec-postgresql/pg_show_plans#29]
Greetings. I noticed the following behaviour while using pgsp: if a certain query shows more than 2 levels of nested queries, level 1 plan gets every subsequent level plan joined to it, and the same happens to any level higher than 1 (see the test output). 
I made a small test to replicate the issue. 
```
CREATE OR REPLACE FUNCTION inner_test3()
	RETURNS int4
	LANGUAGE plpgsql
AS $function$
	BEGIN
	return 1 where pg_sleep(5) is not null;
	END;
$function$;

CREATE OR REPLACE FUNCTION inner_test2()
	RETURNS int4
	LANGUAGE plpgsql
AS $function$
	declare 
	a text;
	begin
	select gen_random_uuid() into a where inner_test3() = 1;
	return 1;
	END;
$function$;

CREATE OR REPLACE FUNCTION inner_test()
	RETURNS int4
	LANGUAGE plpgsql
AS $function$
	BEGIN
	return inner_test2();
	END;
$function$;
```
 After creating the functions we need two open db connections. In one run `select inner_test();` , and in the other one run`select * from pg_show_plans order by pid, level asc` until a plan for this query with three level shows up. 
It consistently gives out the following output: 

pid | level | userid | dbid | plan
-- | -- | -- | -- | --
11126 | 0 | 2777805 | 13726 | Result  (cost=0.00..0.26 rows=1   width=4)
11126 | 1 | 2777805 | 13726 | Result  (cost=0.25..0.27 rows=1   width=16)
| | | | |One-Time Filter: (inner_test3() =   1)**Result  (cost=0.00..0.01 rows=1   width=4)**
| | | | |**One-Time Filter:   (pg_sleep('5'::double precision) IS NOT NULL)**
11126 | 2 | 2777805 | 13726 | **Result  (cost=0.00..0.01 rows=1   width=4)**
 | | | || **One-Time Filter:   (pg_sleep('5'::double precision) IS NOT NULL)**

As you can see, level 1 plan got level 2 joined to it. 
If this is an intended behaviour, can you make it use some sort of the separator between plan levels to be able to understand where each nested plan starts? 

The database info: PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

**Comment by kovmir** [comment]
This is a bug, not a feature. Thank you for a reproducible test.
