### ISSUE TITLE
Package in PGDG Repo

### ISSUE THREAD

**Issue by glushakov** [cybertec-postgresql/pg_show_plans#37]
Hi, thanks for the extension!
For some reason, there is no extension  in the PGDG repository for Postgres 15 (RHEL ), but for other versions it is there.
It should be?
https://download.postgresql.org/pub/repos/yum/15/redhat/rhel-8-x86_64/    -- missed
https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-8-x86_64/  -- it's here

**Comment by kovmir** [comment]
I am not responsible for PGDG packages, please contact [the package maintainer](https://github.com/devrimgunduz).
