### ISSUE TITLE
Start Disabled GUC Option

### ISSUE THREAD

**Issue by kmoppel** [cybertec-postgresql/pg_show_plans#4]
As such troubleshooting / debugging is not always used and has a small performance impact, would be nice if the extension could start in disabled mode and one could enable it when the need arises with pg_show_plans_enable().
An alternative is of course to disable the extension from "shared_preload_libraries", but this requires server restart which might not work for all.

**Comment by legrandlegrand** [comment]
hello,

in pg_stat_statements extension, thoses aspects are managed using a GUC:
pg_stat_statement.track = 'all' || 'top' || 'none'
maybe this could be reused to answer your need:
pg_show_plans.track = 'none' in configuration at startup with the extension defined in shared_preload_libraries.
then 
set pg_show_plans.track = 'all' or pg_show_plans_enable() could be used to start it on demand.

Regards
PAscal

**Comment by legrandlegrand** [comment]
Hello,
Here is a patch trying to answer this question by adding pg_show_plans.startup_enable GUC:

[pg_show_plans.startup_enable.diff.txt](https://github.com/cybertec-postgresql/pg_show_plans/files/4469058/pg_show_plans.startup_enable.diff.txt)

or
https://github.com/legrandlegrand/pg_show_plans/pull/1

**Comment by unInstance** [comment]
Alright, I got it. [GUC](https://www.postgresql.org/docs/current/acronyms.html) variable disables the extension locally, and shared structure variable disables the extension globally (for all clients).
