### ISSUE TITLE
Does pg_show_plans support PG major version 17? 

### ISSUE THREAD

**Issue by jasonchenTJ** [cybertec-postgresql/pg_show_plans#43]
Hi Guys,

Just would like to know:  if the last release version of pg_show_plans support PG major version 17? 

Thanks
Jason

**Comment by kovmir** [comment]
[Yet, it does](https://github.com/cybertec-postgresql/pg_show_plans/actions/runs/11092377570/job/30817337293) support PostgreSQL version 17.

**Comment by jasonchenTJ** [comment]
@kovmir Thanks for your confirm! Have a good day or night! :)
