### ISSUE TITLE
wrong CLANG path centos8

### ISSUE THREAD

**Issue by mmuehlbeyer** [cybertec-postgresql/pg_show_plans#7]
Hi,
I've detected a wrong path for CLANG in the Makefile.global on Centos 8.
Maybe it depends on Centos 8 or my environment, though I just leave a notice ;)

what I've changed:
    231 #CLANG = /usr/lib64/ccache/clang
    232 CLANG = /usr/bin/clang

after this changed make install works as expected

**Comment by s-hironobu** [comment]
Thanks and I think it is the environment issue.
